### ISSUE TITLE
Help please with the garble

### ISSUE THREAD

**Issue by chikamobina** [NHAS/reverse_ssh#116]
When I set up a new rssh server, I always have a problem installing garble. I download it, put it in $PATH, but it refuses to work in "link --garble" garble could not be found in PATH, with great difficulty, I make it work there, 1 rule ./server must be run without sudo or it will not work. Please tell me the order of commands/actions to make garble in link work easily, I am putting rssh on ubuntu.

**Comment by NHAS** [comment]
I would suggest if you are having issues working out how to do the manual install you use the docker version as it has everything reconfigured.

As for your issues. Sudo defines it's own PATH so that a malicious path won't get carried over when you elevate privs.

If you want to run the rssh as root using sudo you'll need to make sure sudo gives it the correct path.

**Comment by chikamobina** [comment]
Thanks, I'll do better with docker
