### ISSUE TITLE
Check your bitcoin wallet bro

### ISSUE THREAD

**Issue by chikamobina** [NHAS/reverse_ssh#117]
There's a present for you, because you didn't see it.

**Comment by NHAS** [comment]
Uh wow! Thank you very much! 
This is very kind of you.

Is there anything you want to see in rssh that would improve how you use it?

**Comment by NHAS** [comment]
Im currently working on a server command that makes the client/s open a port that is a direct tcp forward back to the server port. 

So when pivoting through networks you can just point clients at each other rather than having to do the SSH `-R` reverse forward repeatedly, or finding a way to talk to the server directly. 

Should make catching rssh client reverse connections when deep in networks easier

**Comment by chikamobina** [comment]
Yes in principle everything we wanted, you added in the latest updates :D nothing comes to mind yet.

**Comment by NHAS** [comment]
Howdy, Im just writing sponsors into the readme. If you wanted me to put up a logo/group name or anything other than chikamobina in there just shoot me a message!
