### ISSUE TITLE
Client execution error under amd64 mac computer (upx issue)

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#135]
When I compile a client with darwin operating system and amd64 architecture, and execute it on a 64-bit mac computer with an Intel chip, an error occurs:

`zsh: segmentation fault`

**Comment by NHAS** [comment]
Howdy, can you confirm that when you compile a client for darwin you're doing `--goarch amd64` (or `GOARCH=amd64` in the make file build)

**Comment by NHAS** [comment]
I cant confirm this myself as I dont have an `arm64` `darwin` platform to test on. But you may also want to try compiling with `--no-lib-c` in link or `CGO_ENABLED=0` for makefile

**Comment by tdragon6** [comment]
Also, I would like to ask about `--no-lib-c` and default compilation, what are their advantages, disadvantages and differences?

**Comment by NHAS** [comment]
Huh, unfortunately that sounds like a problem with upx rather than rssh itself so not sure I can fix that, other than putting a warning on that combo. 

`--no-lib-c` can be helpful on systems that dont use glibc, such as alpine. Golang doesnt require libc to function, but I leave it on by default as thats what go's default is. 

As for benefits of leaving it on. No idea.

**Comment by NHAS** [comment]
Unfortunately as I cant fix this myself and there has been no more information/proposed solutions Im going to close this issue.
