### ISSUE TITLE
Proposal: Session Recording Feature Discussion

### ISSUE THREAD

**Issue by eos175** [NHAS/reverse_ssh#155]
I've implemented session recording functionality in the development branch ([link](https://github.com/eos175/reverse_ssh/tree/dev)). This feature allows users to record terminal sessions in Asciicast format. However, there are some aspects that need discussion:

  -  Storage Location: Where should recorded sessions be stored?
  -  Download Capability: Should users be able to download recorded sessions from the server?
  -  Live Viewing: Asciinema supports live viewing of recorded sessions. Should we consider integrating this functionality?

Your feedback on these points would be greatly appreciated.

**Comment by JSmith-Aura** [comment]
Hi there! 

Thanks so much for your work. I just have a few comments/questions to make before addressing your questions. 

This will *only* work if the user uses the server console rather than the preferred method of jump host (`-J`) and it wouldnt be possible to record the jump host sessions as it uses the typical ssh method of `direct-tcp`.

Do you think this is still useful? 

Additionally, whats to stop you using ascii-cinema to just record the terminal as you're using rssh? Why does this have to be part of the functionality of rssh?

1. Storage Location: Where should recorded sessions be stored?
The only place they could be stored is on the server, I'd recommend just putting them within a seperate folder within the `data` directory, call it `recordings` just make sure people can path traversal it

2. I think it would be best to allow this. But how we should do it is by having the `record` function have a `--read` flag that dumps the file to stdout if the current connection is **not** a server console. 

This means a user can use the ssh `exec` handler to do something like this:
```bash
ssh your.rssh.server record --read your.recording.date > file
```

3. This is definitely outside outside the scope of reverse ssh, it's a bit of a debate whether recording should be part of rssh at all. I just want this project to effectively be something people build off, not a collection of every functionality.

**Comment by eos175** [comment]
Hello,

Yes, this will only work if the user uses the server console using the `--record <filename>` flag.

I acknowledge the redundancy of this feature, as asciinema can always be initiated on the host, and then the file can be downloaded...

The only advantage would be on windows, where it's a bit more complicated, and also that the recording occurs on the server and not on the client. However, adding it would slightly divert the project's focus.

**Comment by NHAS** [comment]
Hi! Unfortunately after giving it a bit more of a think, I think this is outside the scope of the project. 

Thank you so much for your work though, and please contribute to RSSH in the future!
