### ISSUE TITLE
--garble option doesn't work after the latest update 

### ISSUE THREAD

**Issue by x9xhack** [NHAS/reverse_ssh#174]
I tried to find the case and it happens only when I add the --garble option

catcher$ link --goos windows --garble --upx
Error: exit status 1
'# github.com/NHAS/reverse_ssh/cmd/client'
EkvaE4.(*W5Oean).ReadSSHPacket: relocation target Mn3aMa.(*fWGdqLcSj).igWwMId not defined
exit status 2
exit status 1

**Comment by NHAS** [comment]
Ah fuck, that'll be because garble is fucking up the function signature when linking in from the std library. 

https://github.com/NHAS/reverse_ssh/blob/f5d2a6cd8562e5f5ff33551aa37285651b90a309/internal/client/handlers/tun.go#L392

Not entirely sure how to fix this but i'll update if I can get it working

**Comment by NHAS** [comment]
Sweet, thanks for opening the issue. I've raised a PR with garble as they have a problem interpreting the `go:linkname` when reflection is being used. 

You can see it here. 

https://github.com/burrowers/garble/pull/883

I'll do a new release when they've fixed it, or if they take a little while I'll use my fork.

**Comment by x9xhack** [comment]
thanks bro for your swift answer

**Comment by NHAS** [comment]
This is now on main, and I've updated the docker container. If you're using the binary install for the server, please install garble@master, rather than latest :)
