### ISSUE TITLE
Specify only the first few characters

### ISSUE THREAD

**Issue by TechSupportJosh** [NHAS/reverse_ssh#49]
It would be a nice feature if you could just specify the first few characters of the connection ID, similar to how Docker containers work with the first few characters, rather than needing to copy and paste the entire ID to use that :)

**Comment by NHAS** [comment]
Depending on how you're connecting to your clients, this is already a feature. 

If you are using the server console (e.g `ssh -p 3232 your.rssh.server`) you can use `connect` and then tab after the first few matching characters. 

You can also use other aliases for a client rather than having to input the whole ID, I typically use the hostname, unless I've got multiple clients running on one machine. 

E.g

```
ssh -J your.rssh.server:3232 username.hostname
```


As I believe this would be a simple change, I'll look into it. A good break from implementing tuntap :P

**Comment by NHAS** [comment]
Sweet, I've added this to the unstable branch. Have a play around!
