### ISSUE TITLE
deployment optimization

### ISSUE THREAD

**Issue by shanjunmei** [NHAS/reverse_ssh#90]
The client can be precompiled into a static library and embedded in the server. When the client needs to be compiled, the static library can be released or the final client can be compiled directly from memory.

**Comment by NHAS** [comment]
What? I have no idea what this means

**Comment by shanjunmei** [comment]
Maybe it's just cleanliness, so the deployment only needs to put a server-side binary file.

**Comment by NHAS** [comment]
I expect what you mean is embedding the client binary into the server so that when the `--link` command is used it just unpacks or just serves from memory the binary. 
This would allow for a single binary deployment. 

As this project has a docker image that can deploy this, Im not too worried about this. As such Im closing this as not planned.
